.\"Copyright (c) 2013, Oskar Skog <oskar.skog.finland@gmail.com>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"1.  Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\"
.\"2.  Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\"ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\"LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\"CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\"SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\"INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\"CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\"ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\"POSSIBILITY OF SUCH DAMAGE.
.Dd Nov 15, 2013
.Dt PASSWDMANFILES 5
.Os
.Sh NAME
.Nm ~/.passwdman/passwords ,
.Nm ~/.passwdman/honeypots ,
.Nm ~/.passwdman/undoable/ ,
.Nm ~/.passwdman/redoable/ ,
.Nm ~/.passwdman/gui.conf
.Nd data-files for passwdman.
.Sh Pa ~/.passwdman/passwords
The password list.
It is an XML file, you are expected to understand an example of the file.
.Bd -literal
<?xml version='1.0' encoding='UTF-8'?>
<root magic="passwdman" file="passwords" version="0.1">
    <!--The attribute 'magic' may not be changed.
    The major version may not be greater than zero.
    The attribute 'file' is used to make sure that it is the right file.-->
    <passwd name="What the password is for" value="top_secret"/>
    <passwd name="TEST" value="0123456789">
        <!--A 'passwd'-element is allowed to contain a 'meta'-element.-->
        <meta type="10" minlength="4" maxlength="255"/>
        <!--type == "human":
                Human generated password.
            type == "10":
                Digits only.
            type == "64":
                Digits, big letters, small letters, underscores and
                exclamation marks.
            'minlength' is the minimal length required for the password.
            'maxlength' is the maximal length allowed for the password.
            
            The meta-data is used when updating the password.-->
    </passwd>
</root>
.Ed
.Sh Pa ~/.passwdman/honeypots
The list of honeypots.
The honeypots are fake-passwords, to help catching crackers.
This too is a XML file.
.Bd -literal
<?xml version='1.0' encoding='UTF-8'?>
<root file="honeypots" magic="passwdman" version="0.1">
    <!--look at ~/.passwdman/passwords-->
    <honeypot value="BadPassword"/>
    <honeypot value="putme_injail_ifi_typethis"/>
</root>
.Ed
.Sh Pa ~/.passwdman/undoable
Backups.
The
.Fn undo
function looks for the newest file and doesn't care about the filename.
If
.Qq passwords
is in the filename, the file is a backup of 
.Pa ~/.passwdman/passwords .
If
.Qq honeypots
is in the filename, the file is a backups of
.Pa ~/.passwdman/honeypots .
It copies the current state to
.Pa ~/.passwdman/redoable
before it restores from the backup.
.Sh Pa ~/.passwdman/redoable
The opposite of
.Pa ~/.passwdman/undoable .
The function is
.Fn redo .
.Sh Pa ~/.passwdman/gui.conf
The GUI configuration file:
.Bd -literal
#Configuration file for passwdmangui.
#If there is any number-sign in a line, the line is a comment.
This is a comment. #
#It knows about 'show_passwd', 'true' and 'false'.
 #It is case sensitive.
show_passwd false
.Ed
.Sh SEE ALSO
.Xr passwdmancli 1 ,
.Xr passwdmangui 1
and
.Xr passwdmanapi 3 .
.Sh BUGS
The documentation.
.Sh AUTHOR
Written by
.An Oskar Skog Aq oskar.skog.finland@gmail.com .
.Pp
Please, send patches, questions, bug reports and wish-lists.