.\"Copyright (c) 2013, 2014, Oskar Skog <oskar.skog.finland@gmail.com>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"1.  Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\"
.\"2.  Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\"ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\"LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\"CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\"SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\"INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\"CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\"ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\"POSSIBILITY OF SUCH DAMAGE.
.Dd Jan 27, 2014
.Dt PASSWDMANCLI 1
.Os
.Sh NAME
.Nm passwdmancli
.Nd CLI for storing, generating and updating passwords and honeypots.
.Sh SYNOPSIS
.Nm
.Op Fl i
.Op Fl -interactive
.Op Fl B
.Op Fl -single-backup
.Op Ar infile
.Sh DESCRIPTION
.Ar infile
is the file
.Nm \"passwdmancli
will read its commands from, if
.Ar infile
is omitted
.Nm \"passwdmancli
will read from standard input.
.Fl i
or
.Fl -interactive
must be specified if you want the commands
.Ic undo
and
.Ic redo ,
or if you want
.Nm
to stay alive after an error.
.Pp
If you specify the option
.Fl B
or
.Fl -single-backup ,
every change that has been done, will be removed by TWO undos.
.Pp
.Nm
reads its input as colon separated values.
Quotes are either forbidden or optional (look at 
.Fn unquote
in
.Xr passwdmanapi 3
).
Integers are created with the python built-in
.Fn int .
All commands are listed in
.Sx COMMANDS .
The first command you really should use is
.Qq esc:on .
If the line begins with a number-sign, the line will be ignored.
If the line begins with a pipe-sign, it will write the rest of the line to
standard output.
.Pp
All outputs that are prefixed with an exclamation mark are error messages.
All outputs that are prefixed with a number sign are messages for a human
user.
All other outputs are prefixed with their command (not their arguments),
using dots instead of colons, followed by a question mark.
.Pp
Beware of whitespace.
The whitespace comes after colons and/or question marks and before quotes.
.Pp
The passwords have meta-data.
They have a minimum required length and a maximum allowed length.
They also have a type which is one of:
.Bl -diag
.It "10"
The password may only use digits.
.It "64"
The password can use big letters, small letters, digits, underscores and
exclamation marks.
.It "human"
The password is human generated.
.El
.Pp
The
.Qq honeypots
are weak passwords intended to be used as traps.
It was a poor choice of name, but it grew legs and glued its feet to the
ground.
.Pp
WARNING: If a command accepts a
.Va name
and
.Va index
argument, any string of digits will be treated as an index.
.Sh COMMANDS
.Bl -tag
.It "bells"
Show message about the bells and whistles.
.It "bugs"
Show message about wasps and mosquitoes.
.It "esc:off"
Disable really simple escapes for quoted strings.
.It "esc:on"
Enable really simple escapes for quoted strings.
They are only useful for escaping quotes.
.It "hell"
Synonym for
.Ic "verbose:on" .
.It "help"
Help message.
.It "honeypot:add:'value'"
Add a new honeypot with the value
.Va value .
.It "honeypot:help"
Help message.
.It "honeypot:list"
List all honeypots.
Returns multiple lines of:
.Qq honeypot.list? ,
the index, a colon and the value surrounded by single quotes.
.It "honeypot:pick"
Pick a honeypot.
Returns a line of:
.Qq honeypot.pick?
followed by the honeypot surrounded by single quotes.
.It "honeypot:pick:n:'sep'"
Pick
.Va n
honeypots and separate them with
.Va sep .
Returns a line of:
.Qq honeypot.pick?
followed by the separator-separated honeypots surrounded by single quotes.
.It "honeypot:pickl:n"
Pick
.Va n
honey-pots, escape and quote (single quotes).
Returns a line of
.Qq honeypot.pickl?
followed by the quoted honey-pots separated with commas.
.It "honeypot:remove:'value'"
Remove the honeypot with the value
.Va value .
.It "honeypot:remove:index"
Remove the honeypot at
.Va index .
WARNING: The indexes of the following honeypots will be decreased by one!
.It "passwd:add:type:minlength:maxlength:'name'"
Add a new password for
.Va name ,
with at least
.Va minlength
letters, but no more than
.Va maxlength .
If
.Va type
is
.Qq 10 ,
the password will only contain digits.
If
.Va type
is
.Qq 64 ,
the password will contain big letters, small letters, digits, underscores and
exclamation marks.
It will not give any output.
.It "passwd:add_human:'name'"
Add a human generated password for
.Va name .
It will read the password on a new line.
It will not give any output.
.It "passwd:get:'name'"
Returns a line of:
.Qq passwd.get?
followed by the value of the password for
.Va name
surrounded by single quotes.
.It "passwd:get:index"
Returns a line of:
.Qq passwd.get?
followed by the value of the password at
.Va index
surrounded by single quotes.
.It "passwd:help"
Help message.
.It "passwd:list"
List all passwords.
Returns multiple lines of:
.Qq passwd.list? ,
the index, a colon and the name surrounded by single quotes.
.It "passwd:meta:'name'"
Get the meta-data for the password for
.Va name .
Returns a line of:
.Qq passwd.meta? ,
the type surrounded by single quotes, a colon, the minimum length for the
password surrounded by single quotes, a colon and the maximum length for the
password surrounded by single quotes.
.It "passwd:meta:index"
Get the meta-data for the password at
.Va index .
Returns a line of:
.Qq passwd.meta? ,
the type surrounded by single quotes, a colon, the minimum length for the
password surrounded by single quotes, a colon and the maximum length for the
password surrounded by single quotes.
.It "passwd:remove:'name'"
Remove the password for
.Va name .
.It "passwd:remove:index"
Remove the password at
.Va index .
WARNING: The indexes of the following passwords will be decreased by one!
.It "passwd:update:'name'"
Update the password for
.Va name
using its meta-data.
Returns a line of:
.Qq passwd.update? ,
the old password, a colon and the new password.
.It "passwd:update:index"
Update the password at
.Va index
using its meta-data.
Returns a line of:
.Qq passwd.update? ,
the old password, a colon and the new password.
.It "passwd:update_meta:type:min:max:'name'"
Do the same thing as
.Ic "passwd:update:'name'" ,
but use
.Va type ,
.Va min ,
and
.Va max
as meta-data, instead of the passwords own (which might not even exist).
.It "passwd:update_meta:type:min:max:index"
Do the same thing as
.Ic "passwd:update:index" ,
but use
.Va type ,
.Va min ,
and
.Va max
as meta-data, instead of the passwords own (which might not even exist).
.It "pb:on"
Enable progress-counters.
start is
.Qq Number-sign, tab, zero, percent.
Progress is
.Qq Enough backspaces, integer decimal digits, percent.
Stop is
.Qq Newline.
.It "pb:off"
Disable progress-counters.
.It "redo"
Opposite of
.Ic undo .
.It "undo"
CLI undo button; restore from latest auto-generated backup.
.It "verbose:on"
Enable verbose mode; release mosquitoes from hell that will be noisy and give
you a headache.
.It "verbose:off"
Disable verbose mode; kill the mosquitoes.
.It "whistles"
Show message about the bells and whistles.
.El
.Sh FILES
.Pa ~/.passwdman/passwords
is a XML file containing all passwords.
.Pp
.Pa ~/.passwdman/honeypots
is a XML file containing all honeypots.
.Pp
.Pa ~/.passwdman/undoable
is a directory full of backups.
.Pp
.Pa ~/.passwdman/redoable
is a directory full of backups.
.Sh DIAGNOSIS
All error messages are sent to standard output and are prefixed with an
exclamation mark.
.Bl -diag
.It "!syntax error"
Bad speling or incorrect usage.
The next line of output will be the offending input prefixed with an
exclamation mark.
.It "!no meta"
The command requires meta-data, but the password doesn't have any.
.It "!not found"
Not found or index out of range
.El
.Sh SEE ALSO
.Xr passwdmanapi 3 ,
.Xr random 4 ,
.Xr urandom 4 ,
.Xr passwdmanfiles 5
.Sh BUGS
Mosquitoes:
.Bl -bullet
.It
If verbose mode is enabled the message
.Qq #READY
is written too many times.
.El
.Sh SECURITY
.Nm
uses
.Xr random 4
or
.Xr urandom 4
for everything.
.Sh AUTHOR
Written by
.An Oskar Skog Aq oskar.skog.finland@gmail.com .
.Pp
Please send patches, questions, bug reports and wish-lists.